name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - user: actions/checkout@v3
        with:
          fetch-depth: 0
      - user: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Install PNPM
        run: npm install -g pnpm

      - run: pnpm install

      - name: Build
        run: pnpm docs:build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/.vitepress/dist
